spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pov
    username: root
    password: root1234
  jpa:
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 3000ms

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucketName: bucket-uplus-127
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  token:
    secretKey: "urecapointofviewsurecapointofviewsurecapoin"

TMDb:
  access: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwOGVjMDViOTA3NjM5NTg3ODViMzQ3NGQ5Y2VlNTM3YiIsIm5iZiI6MTczMjcxMjgyMy40MjQ2NDk1LCJzdWIiOiI2NzM0MGEzMzc2YWYzYWU3YjYzOGIwYzUiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.DRhXvpF7u3F3X1t54qR_56Oq93xVciy7XexDZI5dTAQ"

firebase:
  config:
    path: firebase/firebase-service-account.json