spring:
  application:
    name: pov

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1

  servlet:
    multipart:
      max-file-size: 10MB      # 단일 파일 크기 제한
      max-request-size: 50MB   # 전체 요청 크기 제한
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

springdoc:
  swagger-ui:
    path: /api/docs
    groups-order: desc
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  show-actuator: true
  default-consumes-media-type: application/json

management:
  endpoints:
    web:
      base-path: /api/actuator
