spring:
  application:
    name: pov

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_ADMIN_USERNAME}
    password: ${DB_ADMIN_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration  # 마이그레이션 파일 위치
    baseline-version: 1