spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_ADMIN_USERNAME}
    password: ${DB_ADMIN_PASSWORD}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucketName: bucket-uplus-127
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  token:
    secretKey: "urecapointofviewsurecapointofviewsurecapoin"