name: AWS CI/CD TEST

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: pov-s3-01

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경 변수 등록 테스트
      - name: Test application.yml variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}"
          echo "DB_ADMIN_USERNAME=${{ secrets.DB_ADMIN_USERNAME }}"
          echo "DB_ADMIN_PASSWORD=${{ secrets.DB_ADMIN_PASSWORD }}"
          cat src/main/resources/application.yml
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_ADMIN_USERNAME: ${{ secrets.DB_ADMIN_USERNAME }}
          DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}

      # Gradle 권한 부여 및 실행
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # 애플리케이션 실행 및 환경 변수 테스트
      - name: Run Application and Test
        run: |
          java -jar build/libs/your-app.jar &
          sleep 10
          curl http://localhost:8080/actuator/health
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_ADMIN_USERNAME: ${{ secrets.DB_ADMIN_USERNAME }}
          DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}

      # AWS 권한 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # S3 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/your-app.jar s3://$AWS_S3_BUCKET/
